sudo: required
dist: trusty
language: java
script:
  if [ "$TRAVIS_BRANCH" == "release" ]; then
  export version=`grep "^self" conf/dependencies.yml | awk '{print $4,"-",$5}' | sed 's/ //g'`;
  zip -r ${version}.zip app conf lib src *.md LICENSE play.plugins;
  curl -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" -X PUT --upload-file ${version}.zip https://nexus.sismics.com/repository/sismics/${version}.zip;
  fi
